### ISSUE TITLE
Time stamp popup not going away.

### ISSUE THREAD

**Issue by krypto5863** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#1]
![image](https://user-images.githubusercontent.com/29824718/61494580-8560c680-a984-11e9-8d56-2c219fee6c6b.png)
As it says on the tin. They remain until I switch channels. Also sometimes the client won't scroll down automatically when a new message is shown and an edit was made.

**Comment by ShiiroSan** [comment]
The edit text doesn't look like the one used on NoDeleteMessages.

**Comment by krypto5863** [comment]
> The edit text doesn't look like the one used on NoDeleteMessages.

And you're completely right. Seems I've made a mistake. Thanks.
