### ISSUE TITLE
NoDeleteMessages partly broken

### ISSUE THREAD

**Issue by CIosure** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#16]
Alright so quick heads up but this has been happening for a while and not just for me, edit works fine as of now, but the delete doesn't work as well, once a message is deleted it's supposed to turn red and half transparent, for people right now it doesn't turn red and just stays, this is really annoying, fix coming any time soon?

**Comment by wefalltomorrow** [comment]
Dupe: #12

**Comment by Hiroshi18** [comment]
It was fixed on this PR https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/pull/18 made by ShiiroSan

You could manually use it manually for now till the maintainer accept the PR

Go to your plugin folder and copy and paste the code in https://github.com/ShiiroSan/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/NoDeleteMessages.plugin.js to you local plugin file NoDeleteMessages.plugin.js t

**Comment by ShiiroSan** [comment]
Fixed by #18
