### ISSUE TITLE
Plugin not working (x4 Issues)

### ISSUE THREAD

**Issue by Stoin0001** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#20]
- My Plugin page briefly went blank as well. Now I can see it. After I enabled the plugin a second time after Discord crashed, I cannot disable it. I had to delete it from the folder.

- Edited messages show the first version of an edited message and not the newer version(s).
Screenshot: http://prntscr.com/puiu5r

- Deleted messages appear normal (no red text color) and remain on the screen. Looks like a normal message.
Screenshot: http://prntscr.com/puiu88

*Closed on accident when trying to add a fourth issue.
- After removing the plugin and restarting my client multiple times, none of my edits or deletions appear to have gone through despite my audit log and other bot logging that they did; may have harmed Discord client files.

**Comment by Stoin0001** [comment]
> 
> 
>     * My Plugin page briefly went blank as well. Now I can see it. After I enabled the plugin a second time after Discord crashed, I cannot disable it. I had to delete it from the folder.
> 
>     * Edited messages show the first version of an edited message and not the newer version(s).
>       Screenshot: http://prntscr.com/puiu5r
> 
>     * Deleted messages appear normal (no red text color) and remain on the screen. Looks like a normal message.
>       Screenshot: http://prntscr.com/puiu88

**Comment by ShiiroSan** [comment]
Fixed by #18
