### ISSUE TITLE
NoDeleteMessages small glitch

### ISSUE THREAD

**Issue by yorik100** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#3]
![image](https://user-images.githubusercontent.com/16320315/61663785-ac473180-acd1-11e9-99f7-1b25174d2ef0.png)
Test2 shouldn't show in this color, it should show in the same color than Test

**Comment by yorik100** [comment]
![image](https://user-images.githubusercontent.com/16320315/61663917-f7f9db00-acd1-11e9-8e9b-9283dc6528aa.png)
Same without deleting the message

**Comment by ShiiroSan** [comment]
Issue is patched, wait for the update.

**Comment by yorik100** [comment]
![image](https://user-images.githubusercontent.com/16320315/62172736-9e2d8c80-b333-11e9-8aee-1d218d1ddf8d.png)
Not really fixed, it still behaves as the 2nd and 3rd messages were only modified and not modified and deleted

**Comment by Hiroshi18** [comment]
It was fixed on this PR https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/pull/18 made by ShiiroSan

You could manually use it manually for now till the maintainer accept the PR

Go to your plugin folder and copy and paste the code in https://github.com/ShiiroSan/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/NoDeleteMessages.plugin.js to you local plugin file NoDeleteMessages.plugin.js t
