### ISSUE TITLE
[ShiiroSan's NoDeleteMessages] Edited reply displays edited replied-to message

### ISSUE THREAD

**Issue by KaKi87** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#33]
Hello @ShiiroSan,

First of all, thank you for maintaining Mega-Mewthree's NoDeleteMessages plugin, and sorry to both of you for reporting an issue *here* but I didn't had a choice.

---

When editing a message replying to another, the following unexpected behavior occurs :
- the original message is keeps displayed in non-edited state
- the message being replied to is displayed as the original one in edited state
- the edited message is displayed as an edit of the message being replied to

![](https://user-images.githubusercontent.com/21284089/103570010-9c70dc80-4ec8-11eb-9893-af093bc055b1.png)

---

Thanks.

Finally, I see you're from France, as am I, so we can talk in French if you would like.

PS : your website is showing Apache's default page ^^

**Comment by ShiiroSan** [comment]
Thanks for the issue report. Really like to read a so nicely made issue report.
One of the buddy from Discord already told me about it, I still have to patch it but tbh it's not on my todo list, I've many other projects I'm working on and just trying to keep a _pretty much sometimes working_ version for NDM. If I've some spare time I wanna waste I'll fix this issue. 

PS: Yeah, making a clean website is part of my others projects... And not on the toptier part 😞

**Comment by KaKi87** [comment]
Thank you for answering so quickly and for appreciating my report, I try to make as much as effort as I can to honour the open source spirit and I understand your situation.
++

**Comment by ShiiroSan** [comment]
Fixed, still thank you for your issue report.

**Comment by KaKi87** [comment]
Nice, thank you ! 🙂
