### ISSUE TITLE
Meta was not found

### ISSUE THREAD

**Issue by Jimbo220** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#5]
Installed the plugin but now I get Meta was not Found on discord startup and the plugin will not activate.

**Comment by ShiiroSan** [comment]
Are you sure you have download .plugin.js file?

**Comment by Jimbo220** [comment]
Yes I downloaded the file.

**Comment by Bentechy66** [comment]
It appears that BetterDiscord may be blocking this plugin again. Try changing `name` in your META to something other than what it is, for example `KeepDeletedMessages`, and also change the class name and the `getName` method.

**Comment by RainGH** [comment]
i also ran into this issue, you need to navigate to the file, .plugin.js, then right click on the RAW button at the topright and save link as. It's likely you are downloading the wrong file?

**Comment by astrmlptr** [comment]
Got the same issue. Have downloaded and used this plugin for 2 months with no problem; recently it suddenly doesn't work. After reinstalling betterdiscord, I got META was not found instead. Help?
