### ISSUE TITLE
No delete messages doesn't work anymore?

### ISSUE THREAD

**Issue by Badr40** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#6]
I don't know why, but even though i enabled + updated No Delete Messages, it won't work and it won't show me the deleted messages. Please help.

**Comment by ShiiroSan** [comment]
Have you installed zeresPluginLibrary? Do you have any error? Give as much information as you can, without nobody could help you.

**Comment by Badr40** [comment]
Sorry, my problem has been solved. Thanks anyways!
